### ISSUE TITLE
Resizing window breaks terminal

### ISSUE THREAD

**Issue by liam4** [WHCO/FOS#6]
For instance, if I resize the window it throws an error (reformatted):

```
Traceback (most recent call last):
File "ui.py", line 27, in <module>
  input_data = term.do_input(prompt="$ ")
File "/Users/towerofnix/Documents/FOS-Clone/fos/api/cl/terminal.py", line 64, in do_input
  self.cur_input += chr(character_code)
ValueError: chr() arg not in range(256)
```

This is what the window looks like when I resize it(!):

![Broken window](https://cloud.githubusercontent.com/assets/9948030/10454305/1e290e90-718a-11e5-9317-e788011f7d9f.png)

Instead we should handle the specific characters sent (Windows' codes are probably different from OS X's codes) and resize the UI manually.

**Comment by liam4** [comment]
The only way I can get out of that ruined window is via a hard `towerofnix$ reset`.

**Comment by DatOneLefty** [comment]
maybe we should have a special set of keys (ctrl + r) to redraw the terminal
